lib: [
  "_build/install/default/lib/Game/META"
  "_build/install/default/lib/Game/board.ml"
  "_build/install/default/lib/Game/board.mli"
  "_build/install/default/lib/Game/dune-package"
  "_build/install/default/lib/Game/game.a"
  "_build/install/default/lib/Game/game.cma"
  "_build/install/default/lib/Game/game.cmi"
  "_build/install/default/lib/Game/game.cmt"
  "_build/install/default/lib/Game/game.cmx"
  "_build/install/default/lib/Game/game.cmxa"
  "_build/install/default/lib/Game/game.ml"
  "_build/install/default/lib/Game/game__Board.cmi"
  "_build/install/default/lib/Game/game__Board.cmt"
  "_build/install/default/lib/Game/game__Board.cmti"
  "_build/install/default/lib/Game/game__Board.cmx"
  "_build/install/default/lib/Game/game__Ui.cmi"
  "_build/install/default/lib/Game/game__Ui.cmt"
  "_build/install/default/lib/Game/game__Ui.cmti"
  "_build/install/default/lib/Game/game__Ui.cmx"
  "_build/install/default/lib/Game/opam"
  "_build/install/default/lib/Game/ui.ml"
  "_build/install/default/lib/Game/ui.mli"
]
libexec: [
  "_build/install/default/lib/Game/game.cmxs"
]
doc: [
  "_build/install/default/doc/Game/README.md"
]
